services:
  - type: web
    name: exam-alchemy-api
    region: singapore
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: "mongodb+srv://saksham:Sa%4012345678@mo.l6elf6u.mongodb.net/examalchemy?appName=MO"

  - type: web
    name: exam-alchemy-app
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build || echo 'No build step'"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://exam-alchemy-api.onrender.com/:path*
      - type: rewrite
        source: /*
        destination: /index.html



